"""TK-119 contract test (pipeline item 20260702-002).

Loads the TS-generated golden fixture (nested 10x12 drive_history, the
CORRECT shape post-fix) and the flat-120 regression fixture (the OLD,
buggy `.flat()` shape) and validates both against schemas.py's
CognitionCycleRequest. Proves the nested shape is accepted and that the
schema still catches a regression back to the flattened array.

Fixtures are generated by:
    npx tsx apps/sylphie/src/services/tensor-inference-adapter.golden-fixture.spec.ts
(run from the repo root) and committed alongside this test.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from pydantic import ValidationError

from schemas import CognitionCycleRequest

_FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _load(name: str) -> dict:
    with open(_FIXTURES_DIR / name, "r", encoding="utf-8") as f:
        return json.load(f)


def test_golden_fixture_exists():
    assert (_FIXTURES_DIR / "cycle-request.golden.json").exists(), (
        "golden fixture missing — run "
        "`npx tsx apps/sylphie/src/services/tensor-inference-adapter.golden-fixture.spec.ts` "
        "from the repo root to (re)generate it"
    )
    assert (_FIXTURES_DIR / "cycle-request.flat-regression.json").exists()


def test_nested_drive_history_validates():
    payload = _load("cycle-request.golden.json")

    # Sanity: the fixture really is nested (10 rows x 12 floats), not flat.
    assert len(payload["drive_history"]) == 10
    assert all(len(row) == 12 for row in payload["drive_history"])

    req = CognitionCycleRequest.model_validate(payload)
    assert req.drive_history is not None
    assert len(req.drive_history) == 10
    assert all(len(row) == 12 for row in req.drive_history)


def test_flat_drive_history_regression_raises():
    payload = _load("cycle-request.flat-regression.json")

    # Sanity: the regression fixture really is the old flattened shape.
    assert len(payload["drive_history"]) == 120
    assert all(isinstance(v, (int, float)) for v in payload["drive_history"])

    with pytest.raises(ValidationError):
        CognitionCycleRequest.model_validate(payload)
