/**
 * Type-safe event builder functions for all six subsystems.
 *
 * CANON §Events: Each builder enforces compile-time that a subsystem only emits
 * event types it owns (via EVENT_BOUNDARY_MAP). Builders auto-set subsystem,
 * timestamp, and schemaVersion to prevent configuration drift.
 *
 * The Extract utility type narrows EventType to only those where
 * EVENT_BOUNDARY_MAP[T] === subsystemName. TypeScript validates this at
 * compile time — passing an invalid event type is a type error.
 *
 * All builders return Omit<SylphieEvent, 'id' | 'timestamp'> to match the
 * IEventService.record() contract. The id is generated by TimescaleDB and
 * timestamp is set by the DB persistence layer, though the builder includes
 * it for the event record.
 *
 * Zero dependencies on NestJS — pure TypeScript event builders.
 */

import type {
  EventType,
  SylphieEvent,
  SubsystemSource,
} from '../../shared/types/event.types';
import { EVENT_BOUNDARY_MAP } from '../../shared/types/event.types';
import type { DriveSnapshot } from '../../shared/types/drive.types';
import type { ProvenanceSource } from '../../shared/types/provenance.types';

// ---------------------------------------------------------------------------
// Event Type Narrowing via Extract
// ---------------------------------------------------------------------------

/**
 * Extract all EventType values where EVENT_BOUNDARY_MAP[K] === subsystem.
 * Used by each subsystem's builder to enforce compile-time boundary checking.
 *
 * Example: DecisionMakingEventType resolves to the union of all event types
 * that DECISION_MAKING is authorized to emit. Attempting to pass any other
 * event type to createDecisionMakingEvent() results in a TypeScript error.
 */
type ExtractSubsystemEventType<T extends SubsystemSource> = {
  [K in EventType]: typeof EVENT_BOUNDARY_MAP[K] extends T ? K : never;
}[EventType];

export type DecisionMakingEventType = ExtractSubsystemEventType<'DECISION_MAKING'>;
export type CommunicationEventType = ExtractSubsystemEventType<'COMMUNICATION'>;
export type LearningEventType = ExtractSubsystemEventType<'LEARNING'>;
export type DriveEngineEventType = ExtractSubsystemEventType<'DRIVE_ENGINE'>;
export type PlanningEventType = ExtractSubsystemEventType<'PLANNING'>;
export type SystemEventType = ExtractSubsystemEventType<'SYSTEM'>;
export type WebEventType = ExtractSubsystemEventType<'WEB'>;

// ---------------------------------------------------------------------------
// Builder Options Interface
// ---------------------------------------------------------------------------

/**
 * Common options accepted by all event builder functions.
 *
 * sessionId: Required. Correlates events across a single interaction session.
 * driveSnapshot: Required. Current drive state at the time of event creation.
 *                CANON Standard 1 (Theater Prohibition) requires this on all events.
 * correlationId: Optional. Chains causal relationships across multiple events
 *                (e.g., INPUT_RECEIVED → RESPONSE_DELIVERED).
 * provenance: Optional. Source of information (SENSOR, GUARDIAN, LLM_GENERATED, etc).
 *             Distinct from subsystem ownership.
 * data: Optional. Event-specific payload. Used for additional structured data
 *       beyond the base SylphieEvent fields. Different event types may include
 *       different data fields — consumers check event.type to decide how to
 *       interpret data.
 */
interface EventBuildOptions {
  readonly sessionId: string;
  readonly driveSnapshot: DriveSnapshot;
  readonly correlationId?: string;
  readonly provenance?: ProvenanceSource;
  readonly data?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Base Builder Implementation
// ---------------------------------------------------------------------------

/**
 * Internal helper: builds a base event with auto-set fields.
 *
 * Called by each subsystem's public builder. Auto-sets:
 *   - subsystem: determined by the type parameter
 *   - timestamp: Date.now() (creation time)
 *   - schemaVersion: 1 (for future versioning)
 *
 * The returned object matches Omit<SylphieEvent, 'id' | 'timestamp'> shape
 * for consumption by IEventService.record(). The timestamp field is included
 * for the full event record, even though it will be overridden by the DB
 * persistence layer.
 *
 * @param type - The event type (pre-narrowed by the calling builder)
 * @param subsystem - The owning subsystem
 * @param opts - Common builder options
 * @returns A typed event object ready for record()
 */
function buildEvent<T extends EventType>(
  type: T,
  subsystem: SubsystemSource,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return {
    // Spread data fields first so base fields always win on conflict.
    // This allows event-specific payload fields (e.g., actionType, confidence)
    // to be persisted to TimescaleDB alongside the standard SylphieEvent fields.
    ...(opts.data ?? {}),
    type,
    timestamp: new Date(),
    subsystem,
    sessionId: opts.sessionId,
    driveSnapshot: opts.driveSnapshot,
    schemaVersion: 1,
    correlationId: opts.correlationId,
    provenance: opts.provenance,
  } as Omit<SylphieEvent, 'id'>;
}

// ---------------------------------------------------------------------------
// Per-Subsystem Builders
// ---------------------------------------------------------------------------

/**
 * Create an event from the Decision Making subsystem.
 *
 * Type parameter T is narrowed by TypeScript to only EventType values where
 * EVENT_BOUNDARY_MAP[T] === 'DECISION_MAKING'. Attempting to pass an event
 * type owned by another subsystem results in a compile-time type error.
 *
 * @param type - A DecisionMakingEventType (compile-time validated)
 * @param opts - Builder options (sessionId, driveSnapshot, optional correlationId, provenance)
 * @returns Omit<SylphieEvent, 'id'>
 */
export function createDecisionMakingEvent(
  type: DecisionMakingEventType,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return buildEvent(type, 'DECISION_MAKING', opts);
}

/**
 * Create an event from the Communication subsystem.
 *
 * Type parameter T is narrowed to DecisionMakingEventType. Compile-time
 * boundary enforcement.
 *
 * @param type - A CommunicationEventType (compile-time validated)
 * @param opts - Builder options
 * @returns Omit<SylphieEvent, 'id'>
 */
export function createCommunicationEvent(
  type: CommunicationEventType,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return buildEvent(type, 'COMMUNICATION', opts);
}

/**
 * Create an event from the Learning subsystem.
 *
 * @param type - A LearningEventType (compile-time validated)
 * @param opts - Builder options
 * @returns Omit<SylphieEvent, 'id'>
 */
export function createLearningEvent(
  type: LearningEventType,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return buildEvent(type, 'LEARNING', opts);
}

/**
 * Create an event from the Drive Engine subsystem.
 *
 * @param type - A DriveEngineEventType (compile-time validated)
 * @param opts - Builder options
 * @returns Omit<SylphieEvent, 'id'>
 */
export function createDriveEngineEvent(
  type: DriveEngineEventType,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return buildEvent(type, 'DRIVE_ENGINE', opts);
}

/**
 * Create an event from the Planning subsystem.
 *
 * @param type - A PlanningEventType (compile-time validated)
 * @param opts - Builder options
 * @returns Omit<SylphieEvent, 'id'>
 */
export function createPlanningEvent(
  type: PlanningEventType,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return buildEvent(type, 'PLANNING', opts);
}

/**
 * Create an event from the System subsystem.
 *
 * System events are for infrastructure concerns: session start/end, migrations,
 * error recovery. Used rarely and with explicit intent.
 *
 * @param type - A SystemEventType (compile-time validated)
 * @param opts - Builder options
 * @returns Omit<SylphieEvent, 'id'>
 */
export function createSystemEvent(
  type: SystemEventType,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return buildEvent(type, 'SYSTEM', opts);
}

/**
 * Create an event from the Web subsystem.
 *
 * Web events are for infrastructure concerns related to HTTP/WebSocket connectivity,
 * health checks, and web-facing metrics. Not learnable (has_learnable: false).
 * Type parameter T is narrowed to only EventType values where
 * EVENT_BOUNDARY_MAP[T] === 'WEB'. Compile-time boundary enforcement.
 *
 * @param type - A WebEventType (compile-time validated)
 * @param opts - Builder options
 * @returns Omit<SylphieEvent, 'id'>
 */
export function createWebEvent(
  type: WebEventType,
  opts: EventBuildOptions,
): Omit<SylphieEvent, 'id'> {
  return buildEvent(type, 'WEB', opts);
}

// ---------------------------------------------------------------------------
// Re-exports for clarity
// ---------------------------------------------------------------------------

/**
 * Exported type aliases for use in subsystem code.
 *
 * Import pattern:
 *   import type { DecisionMakingEventType } from '../events/builders';
 */
export type { EventBuildOptions };
