/**
 * Core vocabulary for Sylphie's World Knowledge Graph.
 *
 * ~1000 high-frequency English words chosen for communicative breadth.
 * These are bootstrapped as Word nodes in the WKG so Sylphie has a
 * foundational vocabulary to work with. Meaning, usage patterns, and
 * relationships between words are learned through experience — the
 * bootstrap only provides the raw lexicon.
 */

export const VOCABULARY: readonly string[] = [
  // ── Function words ────────────────────────────────────────────────
  // Articles
  'a', 'an', 'the',
  // Pronouns
  'i', 'me', 'my', 'mine', 'myself',
  'you', 'your', 'yours', 'yourself',
  'he', 'him', 'his', 'himself',
  'she', 'her', 'hers', 'herself',
  'it', 'its', 'itself',
  'we', 'us', 'our', 'ours', 'ourselves',
  'they', 'them', 'their', 'theirs', 'themselves',
  'this', 'that', 'these', 'those',
  'who', 'whom', 'whose', 'which', 'what',
  'each', 'every', 'all', 'both', 'few',
  'many', 'much', 'some', 'any', 'no',
  'none', 'other', 'another', 'such',
  'something', 'nothing', 'everything', 'anything',
  'someone', 'nobody', 'everyone', 'anyone',
  // Prepositions
  'in', 'on', 'at', 'to', 'for',
  'with', 'from', 'by', 'about', 'of',
  'up', 'down', 'into', 'out', 'over',
  'under', 'between', 'through', 'after', 'before',
  'during', 'without', 'against', 'along', 'around',
  'behind', 'below', 'beside', 'beyond', 'near',
  'off', 'since', 'toward', 'until', 'upon',
  'within', 'above', 'across', 'among',
  // Conjunctions
  'and', 'but', 'or', 'so', 'yet',
  'if', 'because', 'although', 'while', 'when',
  'unless', 'whether', 'though', 'as', 'than',
  // Determiners / quantifiers
  'enough', 'several', 'more', 'most', 'less',
  'least', 'either', 'neither',

  // ── Verbs ─────────────────────────────────────────────────────────
  'be', 'am', 'is', 'are', 'was', 'were', 'been', 'being',
  'have', 'has', 'had', 'having',
  'do', 'does', 'did', 'doing', 'done',
  'say', 'said', 'go', 'went', 'gone',
  'get', 'got', 'make', 'made',
  'know', 'knew', 'known', 'think', 'thought',
  'take', 'took', 'taken', 'see', 'saw', 'seen',
  'come', 'came', 'want', 'look', 'looked',
  'use', 'used', 'find', 'found',
  'give', 'gave', 'given', 'tell', 'told',
  'work', 'worked', 'call', 'called',
  'try', 'tried', 'ask', 'asked',
  'need', 'needed', 'feel', 'felt',
  'become', 'became', 'leave', 'left',
  'put', 'mean', 'meant', 'keep', 'kept',
  'let', 'begin', 'began', 'begun',
  'seem', 'seemed', 'help', 'helped',
  'show', 'showed', 'shown', 'hear', 'heard',
  'play', 'played', 'run', 'ran',
  'move', 'moved', 'live', 'lived',
  'believe', 'believed', 'bring', 'brought',
  'happen', 'happened', 'write', 'wrote', 'written',
  'sit', 'sat', 'stand', 'stood',
  'lose', 'lost', 'pay', 'paid',
  'meet', 'met', 'learn', 'learned',
  'change', 'changed', 'lead', 'led',
  'understand', 'understood', 'watch', 'watched',
  'follow', 'followed', 'stop', 'stopped',
  'create', 'created', 'speak', 'spoke', 'spoken',
  'read', 'allow', 'allowed', 'add', 'added',
  'spend', 'spent', 'grow', 'grew', 'grown',
  'open', 'opened', 'walk', 'walked',
  'win', 'won', 'remember', 'remembered',
  'love', 'loved', 'consider', 'considered',
  'appear', 'appeared', 'buy', 'bought',
  'wait', 'waited', 'die', 'died',
  'send', 'sent', 'build', 'built',
  'stay', 'stayed', 'fall', 'fell', 'fallen',
  'cut', 'reach', 'reached',
  'suggest', 'raise', 'raised',
  'pass', 'passed', 'sell', 'sold',
  'decide', 'decided', 'pull', 'pulled',
  'turn', 'turned', 'hold', 'held',
  'produce', 'produced', 'eat', 'ate', 'eaten',
  'teach', 'taught', 'drive', 'drove', 'driven',
  'start', 'started', 'close', 'closed',
  'break', 'broke', 'broken', 'pick', 'picked',
  'carry', 'carried', 'fight', 'fought',
  'draw', 'drew', 'drawn', 'sleep', 'slept',
  'cause', 'caused', 'point', 'pointed',
  'rest', 'talk', 'talked', 'enjoy', 'enjoyed',
  'cover', 'covered', 'wish', 'wished',
  'drop', 'dropped', 'plan', 'planned',
  'push', 'pushed', 'test', 'tested',
  'touch', 'touched', 'fix', 'fixed',
  'cook', 'cooked', 'wear', 'wore', 'worn',
  'share', 'shared', 'choose', 'chose', 'chosen',
  'catch', 'caught', 'sing', 'sang', 'sung',
  'throw', 'threw', 'thrown', 'hang', 'hung',
  'smile', 'smiled', 'laugh', 'laughed',
  'cry', 'cried', 'miss', 'missed',
  'notice', 'noticed', 'promise', 'promised',
  'wonder', 'wondered', 'guess', 'guessed',
  'agree', 'agreed', 'refuse', 'refused',
  'explain', 'explained', 'surprise', 'surprised',
  'thank', 'thanked', 'accept', 'accepted',
  'finish', 'finished', 'forget', 'forgot', 'forgotten',
  'hurt', 'imagine', 'imagined',
  'repeat', 'save', 'saved',

  // ── Nouns: people & relationships ─────────────────────────────────
  'person', 'people', 'man', 'woman', 'child', 'children',
  'boy', 'girl', 'baby', 'mother', 'father',
  'parent', 'brother', 'sister', 'family', 'friend',
  'teacher', 'student', 'doctor', 'king', 'queen',
  'husband', 'wife', 'son', 'daughter', 'neighbor',
  'stranger', 'group', 'team', 'couple', 'crowd',

  // ── Nouns: body ───────────────────────────────────────────────────
  'head', 'face', 'eye', 'eyes', 'ear', 'nose',
  'mouth', 'hand', 'hands', 'arm', 'leg', 'foot', 'feet',
  'body', 'heart', 'brain', 'hair', 'finger',
  'skin', 'tooth', 'teeth', 'bone', 'back',
  'shoulder', 'knee', 'blood', 'stomach', 'neck',
  'chest', 'lip', 'tongue',

  // ── Nouns: nature & environment ───────────────────────────────────
  'world', 'earth', 'sun', 'moon', 'star',
  'sky', 'water', 'fire', 'air', 'land',
  'sea', 'ocean', 'river', 'lake', 'mountain',
  'tree', 'flower', 'grass', 'rain', 'snow',
  'wind', 'cloud', 'stone', 'rock', 'sand',
  'forest', 'island', 'field', 'garden', 'plant',
  'leaf', 'seed', 'root', 'weather', 'storm',
  'ice', 'dust', 'dirt', 'hill', 'valley',
  'wave', 'spring', 'summer', 'fall', 'winter',

  // ── Nouns: animals ────────────────────────────────────────────────
  'animal', 'dog', 'cat', 'bird', 'fish',
  'horse', 'cow', 'bear', 'lion', 'wolf',
  'rabbit', 'snake', 'mouse', 'deer', 'monkey',
  'elephant', 'whale', 'chicken', 'duck', 'fox',
  'sheep', 'pig', 'bee', 'butterfly', 'frog',
  'insect', 'ant', 'spider', 'turtle', 'owl',

  // ── Nouns: food & drink ───────────────────────────────────────────
  'food', 'bread', 'milk', 'meat', 'fruit',
  'rice', 'egg', 'tea', 'coffee', 'sugar',
  'salt', 'oil', 'butter', 'cheese', 'apple',
  'cake', 'soup', 'drink', 'meal', 'lunch',
  'dinner', 'breakfast', 'vegetable', 'potato', 'juice',
  'pie', 'seed', 'honey', 'chocolate', 'candy',

  // ── Nouns: home & objects ─────────────────────────────────────────
  'house', 'home', 'room', 'door', 'window',
  'wall', 'floor', 'table', 'chair', 'bed',
  'book', 'paper', 'pen', 'phone', 'computer',
  'car', 'bus', 'street', 'road', 'city',
  'town', 'school', 'store', 'box', 'bag',
  'cup', 'glass', 'plate', 'bottle', 'key',
  'clock', 'picture', 'mirror', 'money', 'card',
  'tool', 'machine', 'wheel', 'ship', 'boat',
  'train', 'bridge', 'building', 'office', 'church',
  'farm', 'market', 'hat', 'shoe', 'dress',
  'coat', 'shirt', 'ring', 'bell', 'gift',
  'camera', 'screen', 'lamp', 'rope', 'wire',
  'fence', 'gate', 'ladder', 'blanket', 'pillow',
  'knife', 'fork', 'spoon', 'towel', 'soap',
  'candle', 'basket', 'flag', 'map', 'letter',

  // ── Nouns: abstract & concepts ────────────────────────────────────
  'time', 'day', 'night', 'year', 'month',
  'week', 'hour', 'minute', 'moment', 'morning',
  'afternoon', 'evening', 'today', 'tomorrow', 'yesterday',
  'life', 'death', 'love', 'fear', 'hope',
  'dream', 'idea', 'thought', 'mind', 'word',
  'name', 'story', 'question', 'answer', 'problem',
  'reason', 'truth', 'power', 'force', 'energy',
  'law', 'rule', 'fact', 'part', 'place',
  'way', 'thing', 'number', 'system', 'form',
  'end', 'kind', 'line', 'side', 'case',
  'job', 'game', 'music', 'song', 'sound',
  'color', 'light', 'shape', 'space', 'area',
  'country', 'war', 'peace', 'history', 'art',
  'language', 'news', 'class', 'example', 'order',
  'level', 'age', 'voice', 'bit', 'piece',
  'pair', 'set', 'type', 'sort', 'matter',
  'stuff', 'chance', 'choice', 'difference', 'result',
  'effect', 'care', 'attention', 'interest', 'memory',
  'knowledge', 'experience', 'information', 'situation', 'condition',
  'position', 'direction', 'distance', 'speed', 'size',
  'weight', 'height', 'temperature', 'smell', 'taste',
  'noise', 'silence', 'happiness', 'sadness', 'anger',
  'pain', 'pleasure', 'comfort', 'safety', 'danger',
  'trouble', 'effort', 'success', 'failure', 'mistake',
  'secret', 'lesson', 'purpose', 'meaning', 'value',
  'quality', 'nature', 'science', 'math', 'skill',
  'ability', 'action', 'behavior', 'pattern', 'process',
  'step', 'stage', 'edge', 'corner', 'center',
  'middle', 'front', 'beginning', 'top', 'bottom',
  'surface', 'inside', 'outside',

  // ── Adjectives: size & quantity ───────────────────────────────────
  'big', 'small', 'large', 'little', 'long',
  'short', 'tall', 'wide', 'deep', 'thick',
  'thin', 'heavy', 'full', 'empty', 'whole',
  'half', 'single', 'double', 'extra', 'tiny',

  // ── Adjectives: quality & state ───────────────────────────────────
  'good', 'bad', 'great', 'best', 'worst',
  'nice', 'fine', 'poor', 'rich', 'beautiful',
  'ugly', 'clean', 'dirty', 'clear', 'dark',
  'bright', 'soft', 'hard', 'smooth', 'rough',
  'sharp', 'flat', 'round', 'straight', 'narrow',
  'tight', 'loose', 'safe', 'dangerous', 'strong',
  'weak', 'fast', 'slow', 'hot', 'cold',
  'warm', 'cool', 'wet', 'dry', 'fresh',
  'old', 'young', 'new', 'free', 'easy',
  'difficult', 'simple', 'special', 'important', 'different',
  'same', 'similar', 'certain', 'possible', 'impossible',
  'real', 'true', 'false', 'right', 'wrong',
  'normal', 'strange', 'common', 'rare', 'private',
  'public', 'natural', 'basic', 'main', 'local',
  'general', 'specific', 'current', 'recent', 'final',
  'total', 'serious', 'quiet', 'loud', 'alone',
  'alive', 'dead', 'open', 'closed', 'broken',
  'empty', 'busy', 'ready', 'late', 'early',
  'own', 'only', 'sure', 'able', 'likely',

  // ── Adjectives: emotion & character ───────────────────────────────
  'happy', 'sad', 'angry', 'afraid', 'tired',
  'sick', 'hungry', 'thirsty', 'sorry', 'glad',
  'proud', 'nervous', 'calm', 'excited', 'bored',
  'confused', 'careful', 'gentle', 'mean', 'funny',
  'silly', 'crazy', 'lucky', 'perfect', 'terrible',
  'wonderful', 'awful', 'sweet', 'bitter', 'pleasant',
  'comfortable', 'brave', 'shy', 'wise', 'curious',
  'patient', 'honest', 'fair', 'wild', 'quiet',

  // ── Adjectives: color ─────────────────────────────────────────────
  'red', 'blue', 'green', 'yellow', 'black',
  'white', 'brown', 'gray', 'orange', 'pink',
  'purple', 'golden', 'silver',

  // ── Adverbs ───────────────────────────────────────────────────────
  'very', 'really', 'too', 'also', 'just',
  'still', 'already', 'even', 'always', 'never',
  'often', 'sometimes', 'usually', 'probably', 'maybe',
  'perhaps', 'almost', 'quite', 'rather', 'well',
  'hard', 'early', 'late', 'soon', 'again',
  'once', 'twice', 'together', 'apart', 'away',
  'here', 'there', 'everywhere', 'nowhere',
  'now', 'then', 'ago', 'yet', 'else',
  'only', 'about', 'forward', 'far',
  'right', 'please', 'yes', 'no', 'not',
  'okay', 'instead', 'almost', 'especially',
  'finally', 'suddenly', 'slowly', 'quickly', 'carefully',
  'exactly', 'simply', 'clearly', 'actually', 'mostly',

  // ── Numbers & ordinals ────────────────────────────────────────────
  'zero', 'one', 'two', 'three', 'four',
  'five', 'six', 'seven', 'eight', 'nine',
  'ten', 'eleven', 'twelve', 'thirteen', 'fourteen',
  'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen',
  'twenty', 'thirty', 'forty', 'fifty', 'sixty',
  'seventy', 'eighty', 'ninety', 'hundred', 'thousand',
  'million', 'first', 'second', 'third', 'last',
  'next',

  // ── Greetings & social ────────────────────────────────────────────
  'hello', 'hi', 'goodbye', 'bye', 'welcome',
  'sir', 'thanks', 'wow', 'oh', 'ah',
  'oops', 'hey', 'hmm', 'ouch', 'yay',
  'uh',

  // ── Question & relation words ─────────────────────────────────────
  'where', 'when', 'why', 'how',
  'here', 'there', 'then', 'so', 'because',

  // ── Additional high-frequency ─────────────────────────────────────
  'lot', 'rest', 'source', 'base', 'role',
  'sense', 'term', 'view', 'issue', 'concern',
  'scene', 'sign', 'mark', 'note', 'figure',
  'model', 'record', 'report', 'page', 'list',
  'test', 'plan', 'point', 'thought', 'period',
  'century', 'past', 'present', 'future', 'forever',
  'season', 'degree', 'measure', 'price', 'cost',
  'rate', 'trade', 'act', 'deal', 'claim',
  'date', 'truth', 'lie', 'wish', 'belief',
  'doubt', 'trust', 'respect', 'honor', 'pride',
  'shame', 'guilt', 'blame', 'praise', 'reward',
  'risk', 'loss', 'gain', 'goal', 'task',
  'duty', 'promise', 'gift', 'trick', 'joke',
  'wave', 'breath', 'tear', 'sweat', 'blood',
] as const;
