/**
 * Events module interfaces: the contract for all TimescaleDB event I/O.
 *
 * CANON §TimescaleDB — The Event Backbone: All five subsystems write to and
 * read from TimescaleDB through this interface. No subsystem may hold a direct
 * TimescaleDB client; all access goes through IEventService.
 *
 * Zero direct dependencies on NestJS — this file is pure TypeScript interfaces
 * so that the contract can be audited without framework knowledge.
 */

import type {
  SylphieEvent,
  EventType,
  LearnableEvent,
  SubsystemSource,
} from '../../shared/types/event.types';

// ---------------------------------------------------------------------------
// Query & filter types
// ---------------------------------------------------------------------------

/**
 * Options for filtering and paginating event queries.
 *
 * All fields are optional. Omitting a field applies no filter on that
 * dimension. startTime / endTime map to TimescaleDB time-bucket boundaries;
 * both are inclusive.
 */
export interface EventQueryOptions {
  /** Restrict results to these event types. Omit for no type filter. */
  readonly types?: readonly EventType[];

  /** Restrict results to events emitted by these subsystems. */
  readonly subsystems?: readonly SubsystemSource[];

  /** Lower bound on event timestamp (inclusive). */
  readonly startTime?: Date;

  /** Upper bound on event timestamp (inclusive). */
  readonly endTime?: Date;

  /** Return only events belonging to this session. */
  readonly sessionId?: string;

  /**
   * Return only events whose correlationId matches this value.
   * Useful for reconstructing a full causal chain from INPUT_RECEIVED
   * through RESPONSE_DELIVERED.
   */
  readonly correlationId?: string;

  /** Maximum number of events to return. Defaults to 100 if not specified. */
  readonly limit?: number;

  /**
   * Number of events to skip before returning results.
   * Used for pagination in combination with limit.
   */
  readonly offset?: number;
}

// ---------------------------------------------------------------------------
// Frequency result
// ---------------------------------------------------------------------------

/**
 * Aggregated event frequency result for a single event type within a window.
 *
 * Returned by queryEventFrequency. The Drive Engine uses this to compute
 * signal strength for drive rules — e.g., how many GUARDIAN_CORRECTION
 * events occurred in the last 10 minutes maps to a guilt drive input.
 */
export interface EventFrequencyResult {
  /** The event type this count applies to. */
  readonly eventType: EventType;

  /** Number of matching events in the window. */
  readonly count: number;

  /** Actual start of the aggregation window (may differ from requested start). */
  readonly windowStartTime: Date;

  /** Actual end of the aggregation window (may differ from requested end). */
  readonly windowEndTime: Date;
}

// ---------------------------------------------------------------------------
// Pattern query
// ---------------------------------------------------------------------------

/**
 * Query specification for planning pattern research.
 *
 * The Planning subsystem uses this to ask: "how many times, in the last
 * N days, have these event types occurred when the context fingerprint
 * matched this pattern?" Results are used in SimulationService to estimate
 * outcome probability.
 *
 * contextFingerprint is an opaque string produced by the Decision Making
 * subsystem that captures salient features of the current context (active
 * drives above threshold, recent action types, time-of-day bucket, etc.).
 */
export interface EventPatternQuery {
  /**
   * Opaque fingerprint of the context under which the pattern is sought.
   * Produced by Decision Making; matched against stored event metadata.
   */
  readonly contextFingerprint: string;

  /** Event types to count in the pattern window. */
  readonly eventTypes: readonly EventType[];

  /** How many days back to search. */
  readonly windowDays: number;

  /**
   * Minimum number of occurrences required for the result to be included.
   * Prevents returning noise matches. Planning subsystem defaults this to 3.
   */
  readonly minOccurrences: number;
}

// ---------------------------------------------------------------------------
// Record result
// ---------------------------------------------------------------------------

/**
 * Return value from IEventService.record().
 *
 * The id is generated by the persistence layer (UUID v4 from TimescaleDB);
 * the timestamp is the wall-clock time of persistence, which may differ
 * slightly from the timestamp the caller placed on the SylphieEvent.
 *
 * Callers that need to reference the event in later queries (e.g.,
 * correlationId chaining) should use this eventId, not any locally generated
 * value.
 */
export interface RecordResult {
  /** UUID v4 assigned by TimescaleDB at insertion time. */
  readonly eventId: string;

  /** Server-side timestamp of the persistence operation. */
  readonly timestamp: Date;
}

// ---------------------------------------------------------------------------
// Core service interface
// ---------------------------------------------------------------------------

/**
 * Core event service interface.
 *
 * All five subsystems write to and read from TimescaleDB exclusively through
 * this interface. No subsystem holds a direct database client.
 *
 * CANON §TimescaleDB — The Event Backbone: every event in the system flows
 * through this service. The interface enforces:
 *   1. Typed event input (SylphieEvent minus generated fields).
 *   2. Explicit query contracts rather than raw SQL in subsystems.
 *   3. Learning subsystem isolation via queryLearnableEvents with SKIP LOCKED.
 *   4. Drive Engine signal access via queryEventFrequency.
 *   5. Planning pattern access via queryPattern.
 *
 * Injection token: EVENTS_SERVICE (see events.tokens.ts).
 */
export interface IEventService {
  /**
   * Record a new event to TimescaleDB.
   *
   * The caller supplies all SylphieEvent fields except `id` and `timestamp`,
   * which are assigned by the persistence layer. The returned RecordResult
   * carries the generated id and server-side timestamp.
   *
   * CANON Immutable Standard 1 (Theater Prohibition): the driveSnapshot field
   * on the event must reflect actual drive state at the time of the call.
   * Callers must not manufacture a snapshot to make the event look different.
   *
   * CANON Immutable Standard 2 (Contingency Requirement): ReinforcementEvent
   * subtypes carry a required actionId. The interface cannot enforce this at
   * the type level because the input type is SylphieEvent — callers emitting
   * reinforcement events must ensure actionId is present before calling record().
   *
   * @param event - All SylphieEvent fields except id and timestamp
   * @returns The generated eventId and server-side timestamp
   * @throws EventsException if the TimescaleDB write fails
   */
  record(event: Omit<SylphieEvent, 'id' | 'timestamp'>): Promise<RecordResult>;

  /**
   * Query events with filtering and pagination options.
   *
   * Returns events in ascending timestamp order (oldest first). Callers
   * processing a time window should supply both startTime and endTime to
   * avoid unbounded scans.
   *
   * @param options - Filter and pagination options
   * @returns Matching events in ascending timestamp order
   * @throws EventsException if the TimescaleDB read fails
   */
  query(options: EventQueryOptions): Promise<readonly SylphieEvent[]>;

  /**
   * Query unprocessed learnable events for the Learning subsystem.
   *
   * Implements FIFO ordering with SELECT FOR UPDATE SKIP LOCKED to prevent
   * multiple concurrent Learning cycles from claiming the same events.
   * Returns at most `limit` events (default 5 per CANON §Subsystem 3 — max
   * 5 learnable events per cycle to prevent catastrophic interference).
   *
   * Only events with hasLearnable = true and processed = false are returned.
   * Callers must call markProcessed() or markProcessedBatch() after consuming
   * each event to release the lock and prevent re-processing.
   *
   * @param limit - Maximum number of events to return. Defaults to 5.
   * @returns Unprocessed learnable events, oldest first, up to limit
   * @throws EventsException if the query or lock acquisition fails
   */
  queryLearnableEvents(limit?: number): Promise<readonly LearnableEvent[]>;

  /**
   * Query event frequency for Drive Engine signal computation.
   *
   * Counts how many events of each requested type occurred within
   * `windowMs` milliseconds before now. The Drive Engine uses this to
   * compute drive rule inputs — e.g., correction frequency maps to guilt
   * drive pressure.
   *
   * Results include one EventFrequencyResult per requested event type,
   * even if the count is zero. This guarantees the caller receives a
   * complete signal vector without needing to handle missing entries.
   *
   * @param eventTypes - Event types to count
   * @param windowMs - Lookback window in milliseconds
   * @returns One frequency result per requested event type
   * @throws EventsException if the aggregation query fails
   */
  queryEventFrequency(
    eventTypes: readonly EventType[],
    windowMs: number,
  ): Promise<readonly EventFrequencyResult[]>;

  /**
   * Query event patterns for Planning subsystem research.
   *
   * Returns raw events matching the pattern specification. The Planning
   * subsystem uses these events to estimate outcome probability in
   * SimulationService.
   *
   * Only patterns meeting query.minOccurrences are returned. If the
   * contextFingerprint has never been seen or has fewer than minOccurrences
   * matching events, the result is an empty array. The caller (SimulationService)
   * is responsible for interpreting sparse data as low confidence.
   *
   * @param query - Pattern specification including fingerprint, types, and window
   * @returns Matching events from the pattern window, oldest first
   * @throws EventsException if the pattern query fails
   */
  queryPattern(query: EventPatternQuery): Promise<readonly SylphieEvent[]>;

  /**
   * Mark a single event as processed by the Learning subsystem.
   *
   * Must be called after the Learning subsystem has consumed a learnable
   * event returned by queryLearnableEvents(). Releases the SELECT FOR UPDATE
   * SKIP LOCKED row lock and sets the processed flag so the event is not
   * returned in future queryLearnableEvents() calls.
   *
   * @param eventId - UUID of the event to mark as processed
   * @throws EventsException if the update fails or eventId is not found
   */
  markProcessed(eventId: string): Promise<void>;

  /**
   * Mark multiple events as processed by the Learning subsystem (batch).
   *
   * Equivalent to calling markProcessed() for each ID, but executes as a
   * single UPDATE statement. Use this when a Learning cycle consumes multiple
   * events to reduce round-trip overhead.
   *
   * Partial failure semantics: if any eventId is not found, the method
   * throws EventsException without marking any events in the batch. The
   * caller should retry individually if partial processing is acceptable.
   *
   * @param eventIds - Array of event UUIDs to mark as processed
   * @throws EventsException if the batch update fails or any eventId is not found
   */
  markProcessedBatch(eventIds: readonly string[]): Promise<void>;
}
