/**
 * Action system types: procedures, candidates, arbitration results, and outcomes.
 *
 * CANON §Subsystem 1 (Decision Making): The central cognitive loop. Action
 * selection is the final output. These types represent the full pipeline from
 * candidate retrieval through arbitration to execution and outcome recording.
 *
 * CANON §Dual-Process Cognition:
 * - TYPE_1: Graph-based retrieval and execution. High confidence, low latency.
 * - TYPE_2: LLM-assisted deliberation. Engaged when Type 1 confidence is insufficient.
 * - SHRUG: No candidate exceeded threshold. Shrug Imperative (Standard 4) applied.
 *
 * CANON Immutable Standard 4 (Shrug Imperative): When nothing is above the
 * dynamic action threshold, Sylphie signals incomprehension rather than
 * selecting a random low-confidence action. Superstitious behavior prevention.
 *
 * Zero dependencies beyond drive.types.ts and provenance.types.ts.
 */

import type { DriveName } from './drive.types';
import type { ProvenanceSource } from './provenance.types';

// ---------------------------------------------------------------------------
// Drive Category
// ---------------------------------------------------------------------------

/**
 * Classification of a drive as core or complement.
 *
 * CANON §Subsystem 4: 4 core drives (always accumulate) + 8 complement drives.
 * Used by the Action Retrieval service to identify which drive motivated a
 * candidate retrieval and log the motivating drive in ActionCandidate.
 */
export type DriveCategory = 'core' | 'complement';

// ---------------------------------------------------------------------------
// Action Procedure Data
// ---------------------------------------------------------------------------

/**
 * The durable representation of an action procedure as stored in the WKG.
 *
 * ActionProcedureData is the "compiled" form of a behavior — a procedure node
 * retrieved from the graph. The Planning subsystem creates new procedure nodes;
 * the Decision Making subsystem retrieves and executes them.
 *
 * CANON §Confidence Dynamics: The confidence field reflects the current
 * ACT-R computed value at retrieval time. Procedures below retrieval threshold
 * (0.50) are not returned by default WKG queries.
 */
export interface ActionProcedureData {
  /**
   * WKG node ID of this procedure. Used for provenance attribution and
   * reinforcement event actionId. REQUIRED on all reinforcement events.
   */
  readonly id: string;

  /** Human-readable name for this action procedure. */
  readonly name: string;

  /**
   * Category of action for diversity tracking.
   * Corresponds to Neo4j labels on the procedure node.
   * Example values: 'ConversationalResponse', 'SocialComment', 'KnowledgeQuery',
   * 'GuardianEngagement', 'SelfCorrection'
   */
  readonly category: string;

  /**
   * A context fingerprint (e.g., embedding vector or semantic hash) representing
   * the situation in which this procedure was originally learned. Used for
   * cosine similarity matching during retrieval and guilt repair attribution
   * (CANON §A.15: "same context_fingerprint with cosine similarity > 0.7").
   */
  readonly triggerContext: string;

  /**
   * Ordered sequence of steps for this procedure.
   * For simple actions this is a single entry; multi-step plans have multiple.
   */
  readonly actionSequence: readonly ActionStep[];

  /**
   * Provenance of this procedure node.
   * TAUGHT_PROCEDURE: Created by guardian teaching.
   * INFERENCE: Emerged through Planning.
   * LLM_GENERATED: Generated by LLM without explicit guardian confirmation.
   */
  readonly provenance: ProvenanceSource;

  /**
   * Current ACT-R confidence at the time this procedure was retrieved.
   * Snapshot — does not update after retrieval (use IConfidenceService.recordUse).
   */
  readonly confidence: number;
}

/**
 * A single step within an action procedure's sequence.
 */
export interface ActionStep {
  /** Ordered index (0-based) of this step in the sequence. */
  readonly index: number;

  /**
   * Step type. Drives which executor handler processes it.
   * Example values: 'LLM_GENERATE', 'WKG_QUERY', 'TTS_SPEAK', 'LOG_EVENT'
   */
  readonly stepType: string;

  /** Step-specific parameters. Narrowed at the executor handler level. */
  readonly params: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Action Candidate
// ---------------------------------------------------------------------------

/**
 * A candidate action assembled for arbitration.
 *
 * An ActionCandidate pairs a retrieved procedure with the computed confidence
 * at retrieval time and the drive that motivated the retrieval. The motivating
 * drive is required for the Ashby Loop 4 analysis — the system needs to know
 * which need was driving candidate generation to evaluate whether execution
 * produced genuine drive relief.
 */
export interface ActionCandidate {
  /**
   * The underlying procedure this candidate is based on.
   * If null, this is a Type 2 candidate with no existing procedure node —
   * the LLM will generate a novel response.
   */
  readonly procedureData: ActionProcedureData | null;

  /**
   * Computed confidence for this candidate at the time of arbitration.
   * For Type 1 candidates: ACT-R confidence of the procedure node.
   * For Type 2 candidates: typically starts at 0.0 (no prior history).
   */
  readonly confidence: number;

  /**
   * The drive that motivated retrieving this candidate.
   *
   * Required for Ashby Loop 4: the system tracks which drive was motivating
   * which actions to detect whether drive relief is actually being achieved
   * by the actions being selected. If Curiosity consistently motivates
   * candidates that don't produce Curiosity relief, that is a diagnostic signal.
   */
  readonly motivatingDrive: DriveName;

  /**
   * How well this candidate's triggerContext matches the current input context.
   * Similarity score in [0.0, 1.0]. Higher = better context match.
   * Used as a tiebreaker when multiple candidates have similar confidence.
   */
  readonly contextMatchScore: number;
}

// ---------------------------------------------------------------------------
// Arbitration Result — Discriminated Union
// ---------------------------------------------------------------------------

/**
 * The result of the Type 1 / Type 2 arbitration process.
 *
 * CANON §Dual-Process Cognition + Standard 4 (Shrug Imperative):
 * Exactly three outcomes are possible:
 *
 * TYPE_1: A graph-based candidate exceeded the confidence threshold and was
 *         selected without LLM involvement. Low latency path.
 *
 * TYPE_2: No Type 1 candidate met threshold; LLM deliberation was invoked.
 *         Must always carry llmRationale for provenance and theater validation.
 *         The LLM cost (latency, tokens) must be reported to the Drive Engine.
 *
 * SHRUG:  No candidate exceeded threshold AND no LLM response was actionable.
 *         Sylphie signals incomprehension. Standard 4 requires this variant —
 *         randomly selecting a low-confidence action is superstitious behavior.
 *
 * This is a discriminated union on the `type` field. Callers should use
 * exhaustive switch statements to ensure all three variants are handled.
 */
export type ArbitrationResult =
  | {
      readonly type: 'TYPE_1';
      /** The selected Type 1 candidate. */
      readonly candidate: ActionCandidate;
    }
  | {
      readonly type: 'TYPE_2';
      /** The selected Type 2 candidate (may have null procedureData for novel responses). */
      readonly candidate: ActionCandidate;
      /**
       * The LLM's reasoning for selecting this candidate.
       * Required for theater validation and post-hoc analysis of LLM influence.
       * CANON §Communication: LLM speaks FOR Sylphie — knowing why helps detect drift.
       */
      readonly llmRationale: string;
    }
  | {
      readonly type: 'SHRUG';
      /**
       * Human-readable reason no candidate was selected.
       * Example: "No Type 1 candidates above threshold (max: 0.43). Type 2 invoked
       * but returned content below theater threshold."
       */
      readonly reason: string;
    };

// ---------------------------------------------------------------------------
// Selected Action
// ---------------------------------------------------------------------------

/**
 * The action that has been committed to execution.
 *
 * Created from the ArbitrationResult after theater validation. If theater
 * validation fails, the action is modified or replaced — SelectedAction
 * always represents an action that passed validation.
 *
 * CANON Standard 1 (Theater Prohibition): Any action flagged as theatrical
 * (expression mismatched with drive state) receives zero reinforcement.
 * The theaterValidated flag records whether the action passed the validator.
 */
export interface SelectedAction {
  /**
   * ID of the procedure node being executed.
   * This is the actionId referenced in all downstream reinforcement events
   * (Standard 2: Contingency Requirement).
   */
  readonly actionId: string;

  /** The arbitration result that produced this action. */
  readonly arbitrationResult: ArbitrationResult;

  /** Timestamp when this action was committed to the executor. */
  readonly selectedAt: Date;

  /**
   * Whether the Theater Prohibition validator approved this action.
   * Actions that fail validation are zero-reinforced regardless of guardian response.
   */
  readonly theaterValidated: boolean;

  /** If theaterValidated is false, the reason from the validator. */
  readonly theaterViolationReason?: string;
}

// ---------------------------------------------------------------------------
// Executor State
// ---------------------------------------------------------------------------

/**
 * The state machine states of the Executor Engine.
 *
 * CANON §Subsystem 1 (Decision Making): The Executor Engine is a state machine.
 * These states represent the phases of the cognitive loop. Only one state is
 * active at a time. Transitions are managed by IExecutorEngine.transition().
 *
 * IDLE:         Waiting for input or drive sensor trigger.
 * CATEGORIZING: Classifying the incoming input.
 * PREDICTING:   Generating predictions about candidate outcomes.
 * ARBITRATING:  Running Type 1 / Type 2 arbitration.
 * RETRIEVING:   Fetching action candidates from the WKG.
 * EXECUTING:    Action dispatched, awaiting completion.
 * OBSERVING:    Monitoring the outcome of the executed action.
 * LEARNING:     Encoding the episode and updating predictions.
 */
export enum ExecutorState {
  IDLE = 'IDLE',
  CATEGORIZING = 'CATEGORIZING',
  PREDICTING = 'PREDICTING',
  ARBITRATING = 'ARBITRATING',
  RETRIEVING = 'RETRIEVING',
  EXECUTING = 'EXECUTING',
  OBSERVING = 'OBSERVING',
  LEARNING = 'LEARNING',
}

// ---------------------------------------------------------------------------
// Action Outcome
// ---------------------------------------------------------------------------

/**
 * The observed outcome of an executed action.
 *
 * Created by the Observation phase of the executor loop. Fed to the Drive
 * Engine via IPC as an ActionOutcomePayload to trigger drive updates.
 *
 * CANON §A.15 (Anxiety Amplification): If anxietyAtExecution > 0.7 and
 * outcome is negative, the Drive Engine applies 1.5x confidence reduction.
 * The anxietyAtExecution field is therefore load-bearing.
 */
export interface ActionOutcome {
  /**
   * The action that was executed.
   * Used for contingency attribution — the Drive Engine needs the actionId
   * to match reinforcement to the correct behavior (Standard 2).
   */
  readonly selectedAction: SelectedAction;

  /**
   * Whether the action produced the predicted result.
   * Drives prediction MAE accumulation and Type 1/2 graduation logic.
   */
  readonly predictionAccurate: boolean;

  /**
   * Absolute prediction error for this outcome in [0.0, 1.0].
   * 0.0 = perfect prediction. 1.0 = complete miss.
   */
  readonly predictionError: number;

  /**
   * The drive effects observed after this action executed.
   * Keyed by DriveName, values are the observed deltas.
   * Partial map — only drives that changed are included.
   */
  readonly driveEffectsObserved: Partial<Record<DriveName, number>>;

  /**
   * Anxiety level at the moment the action was dispatched.
   * Required for CANON §A.15 Anxiety Amplification check in the Drive Engine.
   * Value in [-10.0, 1.0] per CANON drive range.
   */
  readonly anxietyAtExecution: number;

  /** Wall-clock time the outcome was observed. */
  readonly observedAt: Date;
}
